# Site settings
title: Li Hanqian blog
email: 
description: "Musings of a Computer Scientist."
baseurl: ""
url: "http://LiHanqian.github.io"
github_username:  hanqian.li

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
